apiVersion: v1
kind: BuildConfig
metadata:
  name: openshift-tagger
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshift-tagger-custom-builder:latest
  source:
    git:
      ref: master
      uri: ssh://git@github.com/cloudowski/openshift-tagger-custom-builder.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers: {}
